// This class handles the devices connecting to the internal MQTT broker. This includes both device provisioning
// and minimal wrappers for actual data exchange. The device class is responsible for generating/parsing the payload.

import { generateDeployResponse } from './provisioning'
import { TypedEmitter } from 'tiny-typed-emitter'
import { Client, PublishPacket, type Broker } from '../mqtt-broker'
import { ClipDeployMessage, ClipMessage } from './clip'

import log from '@/util/logging'
import { Metadata } from '../thinq'
import type { BridgeMessage } from './bridge-message'

type DeviceEvents = {
    data: (packet: Buffer) => void
    sendData: (buf: Buffer) => void
    close: () => void
}

export class Device extends TypedEmitter<DeviceEvents> {
    // this could be a stream but why bother...
    readonly platform = 'thinq2'

    constructor(
        readonly broker: Broker,
        readonly topic: string,
        readonly id: string,
        readonly meta: Metadata,
    ) {
        super()
    }

    private bridgeMessageListeners = new Set<(message: BridgeMessage) => void>()
    private bridgeSendMessageListeners = new Set<(message: BridgeMessage) => void>()

    onBridgeMessage(listener: (message: BridgeMessage) => void) {
        this.bridgeMessageListeners.add(listener)
    }

    removeBridgeMessageListener(listener: (message: BridgeMessage) => void) {
        this.bridgeMessageListeners.delete(listener)
    }

    emitBridgeMessage(message: BridgeMessage) {
        for (const listener of this.bridgeMessageListeners) {
            try {
                listener(message)
            } catch (err) {
                console.warn('ThinQ2 bridge message listener failed', err)
            }
        }
    }

    onBridgeSendMessage(listener: (message: BridgeMessage) => void) {
        this.bridgeSendMessageListeners.add(listener)
    }

    removeBridgeSendMessageListener(listener: (message: BridgeMessage) => void) {
        this.bridgeSendMessageListeners.delete(listener)
    }

    private emitBridgeSendMessage(message: BridgeMessage) {
        for (const listener of this.bridgeSendMessageListeners) {
            try {
                listener(message)
            } catch (err) {
                console.warn('ThinQ2 bridge send message listener failed', err)
            }
        }
    }

    send(cmd: string, type: number, data: string | object) {
        const messagestr = JSON.stringify({ did: this.id, mid: Date.now(), cmd: cmd, type: type, data: data })
        this.broker.publish(
            { topic: this.topic, retain: false, qos: 0, dup: false, payload: messagestr },
            null /* message generated by the broker itself */,
        )
    }

    send_packet(buf: Buffer) {
        this.emit('sendData', buf)
        this.send('packet', 1, buf.toString('hex'))
    }

    sendBridgeMessage(message: BridgeMessage) {
        this.broker.publish(
            {
                topic: this.topic,
                retain: false,
                qos: 0,
                dup: false,
                payload: message.payload,
            },
            null,
        )
        // Observers run only after the downstream publish. Capture/management
        // failures must never interfere with transparent forwarding.
        this.emitBridgeSendMessage(message)
    }
}

function trimNull(buf: Buffer) {
    if (!buf || !buf.length || buf[buf.length - 1]) return buf
    return buf.subarray(0, buf.length - 1)
}

type ClientWithExtra = Client & {
    deviceObj: undefined | Device
    deployMsg: undefined | ClipDeployMessage
}

type DeviceAcceptorEvents = {
    newDevice: (dev: Device) => void
    dropDevice: (id: string) => void
}

export class DeviceAcceptor extends TypedEmitter<DeviceAcceptorEvents> {
    clientsById: Record<string, Client> = {}
    constructor(readonly broker: Broker) {
        super()

        broker.on('publish', (packet, client) => {
            if (client) {
                log('incoming', packet.topic, packet.payload.toString('utf-8'), 'retain:', packet.retain)
            } else {
                log('outgoing', packet.topic, packet.payload.toString('utf-8'), 'retain:', packet.retain)
                return // don't process outgoing packets further
            }

            try {
                if (packet.topic.indexOf('clip/') >= 0) {
                    const rawPayload = Buffer.from(packet.payload)
                    const payload = JSON.parse(trimNull(rawPayload).toString('utf-8'))
                    this.mqtt(packet.topic, payload, client as ClientWithExtra, {
                        sourceTopic: packet.topic,
                        qos: packet.qos,
                        retain: packet.retain,
                        payload: rawPayload,
                    })
                }
            } catch (err) {
                console.warn(err, packet.payload.toString('hex'))
            }
        })

        broker.on('disconnect', this.disconnected.bind(this))
    }

    mqtt(topic: string, payload: ClipMessage, client: ClientWithExtra, bridgeMessage?: BridgeMessage) {
        // experiment: try to support devices which use other topic formats
        topic = topic.replace(/^.*\/clip/, 'clip')

        if (topic === 'clip/message/devices/' + payload.did) {
            if (payload.cmd === 'completeProvisioning_ack') {
                this.completeProvisioning(payload.did, payload, client)
                return
            }

            if (payload.cmd === 'req_timesync' && client.deployMsg && payload.did === client.deployMsg.did) {
                this.timeSyncRequest(client)
                return
            }

            if (client.deviceObj && payload.did === client.deviceObj.id) {
                if (bridgeMessage) client.deviceObj.emitBridgeMessage(bridgeMessage)

                if (payload.cmd === 'device_packet' && typeof payload.data === 'string') {
                    try {
                        client.deviceObj.emit('data', Buffer.from(payload.data, 'hex'))
                    } catch (err) {
                        console.warn('ThinQ2 device data listener failed', err)
                    }
                }
            }
        }

        if (topic === 'clip/provisioning/devices/' + payload.did) {
            if (payload.cmd === 'preDeploy' || payload.cmd === 'deploy') {
                client.deployMsg = payload as ClipDeployMessage
                this.broker.publish(
                    {
                        topic: 'lime/devices/' + payload.did,
                        retain: false,
                        qos: 0,
                        dup: false,
                        payload: JSON.stringify(generateDeployResponse(payload as ClipDeployMessage)),
                    },
                    null,
                )
            }
        }
    }

    completeProvisioning(deviceId: string, payload: ClipMessage, client: ClientWithExtra) {
        if (!client.deployMsg) {
            console.warn('completeProvisioning_ack received without deploy/preDeploy')
            return
        }

        if (client.deviceObj) {
            console.warn('completeProvisioning_ack received twice?')
            return
        }

        if (this.clientsById[deviceId]) {
            console.warn(`device ${deviceId} already connected, dropping the old one`)
            this.clientsById[deviceId].destroy()
        }

        this.clientsById[deviceId] = client

        const meta: Metadata = {
            modelId: client.deployMsg.kind,
            modelName: client.deployMsg.data?.appInfo?.modelName,
            swVersion: client.deployMsg.data?.appInfo?.softVer,
            deviceType: client.deployMsg.data?.appInfo?.DeviceType,
            modelLanguage: client.deployMsg.data?.appInfo?.modelLanguage,
            countryCode: client.deployMsg.data?.appInfo?.countryCode,
            subCountryCode: client.deployMsg.data?.appInfo?.subCountryCode,
        }

        const dev = new Device(this.broker, 'lime/devices/' + deviceId, deviceId, meta)
        client.deviceObj = dev
        this.emit('newDevice', dev)
    }

    timeSyncRequest(client: ClientWithExtra) {
        const now = new Date()
        const buf = Buffer.alloc(7)
        buf[0] = now.getUTCFullYear() % 100
        buf[1] = now.getUTCMonth()
        buf[2] = now.getUTCDate()
        buf[3] = now.getUTCHours()
        buf[4] = now.getUTCMinutes()
        buf[5] = now.getUTCSeconds()
        buf[6] = now.getUTCDay()

        const deviceId = client.deployMsg?.did
        if (!deviceId) return

        this.broker.publish(
            {
                topic: 'lime/devices/' + deviceId,
                retain: false,
                qos: 0,
                dup: false,
                payload: JSON.stringify({
                    did: deviceId,
                    mid: Date.now(),
                    cmd: 'resp_timesync',
                    type: 1,
                    data: buf.toString('base64'),
                }),
            },
            null,
        )
    }

    disconnected(_client: Client) {
        let client = _client as ClientWithExtra
        if (client.deviceObj) {
            delete this.clientsById[client.deviceObj.id]
            this.emit('dropDevice', client.deviceObj.id)
            client.deviceObj.emit('close')
            client.deviceObj = undefined
        }
    }
}
